# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  image: node:lts
  script:
  - npm install
  - yarn test

deploy:
  stage: deploy
  image: gitlab/dind
  script:
    - docker build -t node-addition-service .
    - docker tag node-addition-service engagementteamci/node-addition-service:gitlab
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push engagementteamci/node-addition-service:gitlab
  only:
      - main
