jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - 14.16.0
      cache: yarn
    - stage: deploy
      services:
        - docker
      before_install:
        - docker build -t engagementteamci/node-addition-service:travisci .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      provider: script
      script: docker push engagementteamci/node-addition-service:travisci
      on:
        all_branches: true
