language: node_js
node_js:
  - 14.16.0
cache: yarn
services:
  - docker

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      before_install:
        - docker build -t engagementteamci/node-unit-tests:travisci .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      provider: script
      script: docker push engagementteamci/node-unit-tests:travisci
      on:
        all_branches: true
