# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy
on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: [main]
    types: 
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Publish Docker
      # You may pin to the exact commit or the version.
      # uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      uses: elgohr/Publish-Docker-Github-Action@3.02
      with:
        name: engagementteamci/node-unit-tests
        username: engagementteamci
        password: ${{ secrets.DOCKERHUBPASSWORD }}
        default_branch: main
        tags: "github-actions"
